# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Flutter Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install system dependencies
        run: sudo apt install clang cmake ninja pkg-config

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build linux --release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build/linux/x64/release/bundle'
